package wg.user.mobileimsdk.server.model.fs;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("manage_depart", "dep_id", ManageDepart.class);
		arp.addMapping("manage_perm", "perm_id", ManagePerm.class);
		arp.addMapping("manage_role", "role_id", ManageRole.class);
		// Composite Primary Key order: perm_id,role_id
		arp.addMapping("manage_role_perm_rel", "perm_id,role_id", ManageRolePermRel.class);
		// Composite Primary Key order: role_id,user_id
		arp.addMapping("manage_role_user_rel", "role_id,user_id", ManageRoleUserRel.class);
		arp.addMapping("manage_user_info", "user_id", ManageUserInfo.class);
		arp.addMapping("news", "id", News.class);
		arp.addMapping("userinfo", "id", Userinfo.class);
	}
}

