package wg.user.mobileimsdk.server.model.fs;

import wg.user.mobileimsdk.server.model.fs.base.BaseImFileMange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImFileMange extends BaseImFileMange<ImFileMange> {
	public static final ImFileMange dao = new ImFileMange().dao();
}
