package wg.user.mobileimsdk.server.model.fs;

import wg.user.mobileimsdk.server.model.fs.base.BaseManageDepart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageDepart extends BaseManageDepart<ManageDepart> {
	public static final ManageDepart dao = new ManageDepart().dao();
}
