package wg.user.mobileimsdk.server.model.fs;

import wg.user.mobileimsdk.server.model.fs.base.BaseManageRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageRole extends BaseManageRole<ManageRole> {
	public static final ManageRole dao = new ManageRole().dao();
}
