package wg.user.mobileimsdk.server.model.fs;

import wg.user.mobileimsdk.server.model.fs.base.BaseManageRolePermRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageRolePermRel extends BaseManageRolePermRel<ManageRolePermRel> {
	public static final ManageRolePermRel dao = new ManageRolePermRel().dao();
}
