package wg.user.mobileimsdk.server.model.fs;

import wg.user.mobileimsdk.server.model.fs.base.BaseManagePerm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManagePerm extends BaseManagePerm<ManagePerm> {
	public static final ManagePerm dao = new ManagePerm().dao();
}
