package wg.user.mobileimsdk.server.model.fs;

import wg.user.mobileimsdk.server.model.fs.base.BaseManageUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageUserInfo extends BaseManageUserInfo<ManageUserInfo> {
	public static final ManageUserInfo dao = new ManageUserInfo().dao();
}
