package wg.user.mobileimsdk.server.model.fs;

import wg.user.mobileimsdk.server.model.fs.base.BaseManageRoleUserRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageRoleUserRel extends BaseManageRoleUserRel<ManageRoleUserRel> {
	public static final ManageRoleUserRel dao = new ManageRoleUserRel().dao();
}
