package wg.user.mobileimsdk.server.model.fs;

import wg.user.mobileimsdk.server.model.fs.base.BaseUserinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userinfo extends BaseUserinfo<Userinfo> {
	public static final Userinfo dao = new Userinfo().dao();
}
