package wg.user.mobileimsdk.server.model.fs.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseManagePerm<M extends BaseManagePerm<M>> extends Model<M> implements IBean {

	public void setPermId(java.lang.Integer permId) {
		set("perm_id", permId);
	}

	public java.lang.Integer getPermId() {
		return get("perm_id");
	}

	public void setPermPath(java.lang.String permPath) {
		set("perm_path", permPath);
	}

	public java.lang.String getPermPath() {
		return get("perm_path");
	}

	public void setPermName(java.lang.String permName) {
		set("perm_name", permName);
	}

	public java.lang.String getPermName() {
		return get("perm_name");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

	public java.lang.String getIcon() {
		return get("icon");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
