package wg.user.mobileimsdk.server.model.fs.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserinfo<M extends BaseUserinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setBirthday(java.lang.String birthday) {
		set("birthday", birthday);
	}

	public java.lang.String getBirthday() {
		return get("birthday");
	}

	public void setMinzu(java.lang.String minzu) {
		set("minzu", minzu);
	}

	public java.lang.String getMinzu() {
		return get("minzu");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setJiguan(java.lang.String jiguan) {
		set("jiguan", jiguan);
	}

	public java.lang.String getJiguan() {
		return get("jiguan");
	}

	public void setChushengdi(java.lang.String chushengdi) {
		set("chushengdi", chushengdi);
	}

	public java.lang.String getChushengdi() {
		return get("chushengdi");
	}

	public void setSourcePath(java.lang.String sourcePath) {
		set("sourcePath", sourcePath);
	}

	public java.lang.String getSourcePath() {
		return get("sourcePath");
	}

	public void setImagePath(java.lang.String imagePath) {
		set("imagePath", imagePath);
	}

	public java.lang.String getImagePath() {
		return get("imagePath");
	}

	public void setRudangshijian(java.lang.String rudangshijian) {
		set("rudangshijian", rudangshijian);
	}

	public java.lang.String getRudangshijian() {
		return get("rudangshijian");
	}

	public void setGongzuoshijian(java.lang.String gongzuoshijian) {
		set("gongzuoshijian", gongzuoshijian);
	}

	public java.lang.String getGongzuoshijian() {
		return get("gongzuoshijian");
	}

	public void setJiankangzhuangkang(java.lang.String jiankangzhuangkang) {
		set("jiankangzhuangkang", jiankangzhuangkang);
	}

	public java.lang.String getJiankangzhuangkang() {
		return get("jiankangzhuangkang");
	}

	public void setZhuanyejishuzhuwu(java.lang.String zhuanyejishuzhuwu) {
		set("zhuanyejishuzhuwu", zhuanyejishuzhuwu);
	}

	public java.lang.String getZhuanyejishuzhuwu() {
		return get("zhuanyejishuzhuwu");
	}

	public void setYouhetechang(java.lang.String youhetechang) {
		set("youhetechang", youhetechang);
	}

	public java.lang.String getYouhetechang() {
		return get("youhetechang");
	}

	public void setQuanrizhijiaoyu(java.lang.String quanrizhijiaoyu) {
		set("quanrizhijiaoyu", quanrizhijiaoyu);
	}

	public java.lang.String getQuanrizhijiaoyu() {
		return get("quanrizhijiaoyu");
	}

	public void setQuanrizhibiyeyuanxiao(java.lang.String quanrizhibiyeyuanxiao) {
		set("quanrizhibiyeyuanxiao", quanrizhibiyeyuanxiao);
	}

	public java.lang.String getQuanrizhibiyeyuanxiao() {
		return get("quanrizhibiyeyuanxiao");
	}

	public void setZaizhijiaoyu(java.lang.String zaizhijiaoyu) {
		set("zaizhijiaoyu", zaizhijiaoyu);
	}

	public java.lang.String getZaizhijiaoyu() {
		return get("zaizhijiaoyu");
	}

	public void setZaizhibiyeyuanxiao(java.lang.String zaizhibiyeyuanxiao) {
		set("zaizhibiyeyuanxiao", zaizhibiyeyuanxiao);
	}

	public java.lang.String getZaizhibiyeyuanxiao() {
		return get("zaizhibiyeyuanxiao");
	}

	public void setXianrenzhiwu(java.lang.String xianrenzhiwu) {
		set("xianrenzhiwu", xianrenzhiwu);
	}

	public java.lang.String getXianrenzhiwu() {
		return get("xianrenzhiwu");
	}

	public void setNirenzhiwu(java.lang.String nirenzhiwu) {
		set("nirenzhiwu", nirenzhiwu);
	}

	public java.lang.String getNirenzhiwu() {
		return get("nirenzhiwu");
	}

	public void setNimianzhiwu(java.lang.String nimianzhiwu) {
		set("nimianzhiwu", nimianzhiwu);
	}

	public java.lang.String getNimianzhiwu() {
		return get("nimianzhiwu");
	}

	public void setJianli(java.lang.String jianli) {
		set("jianli", jianli);
	}

	public java.lang.String getJianli() {
		return get("jianli");
	}

	public void setChengjiangqingkuang(java.lang.String chengjiangqingkuang) {
		set("chengjiangqingkuang", chengjiangqingkuang);
	}

	public java.lang.String getChengjiangqingkuang() {
		return get("chengjiangqingkuang");
	}

	public void setNiandukaohe(java.lang.String niandukaohe) {
		set("niandukaohe", niandukaohe);
	}

	public java.lang.String getNiandukaohe() {
		return get("niandukaohe");
	}

	public void setRenmianliyou(java.lang.String renmianliyou) {
		set("renmianliyou", renmianliyou);
	}

	public java.lang.String getRenmianliyou() {
		return get("renmianliyou");
	}

	public void setGName1(java.lang.String gName1) {
		set("g_name1", gName1);
	}

	public java.lang.String getGName1() {
		return get("g_name1");
	}

	public void setGName2(java.lang.String gName2) {
		set("g_name2", gName2);
	}

	public java.lang.String getGName2() {
		return get("g_name2");
	}

	public void setGName3(java.lang.String gName3) {
		set("g_name3", gName3);
	}

	public java.lang.String getGName3() {
		return get("g_name3");
	}

	public void setGName4(java.lang.String gName4) {
		set("g_name4", gName4);
	}

	public java.lang.String getGName4() {
		return get("g_name4");
	}

	public void setGName5(java.lang.String gName5) {
		set("g_name5", gName5);
	}

	public java.lang.String getGName5() {
		return get("g_name5");
	}

	public void setGName6(java.lang.String gName6) {
		set("g_name6", gName6);
	}

	public java.lang.String getGName6() {
		return get("g_name6");
	}

	public void setGName7(java.lang.String gName7) {
		set("g_name7", gName7);
	}

	public java.lang.String getGName7() {
		return get("g_name7");
	}

	public void setGChengwei1(java.lang.String gChengwei1) {
		set("g_chengwei1", gChengwei1);
	}

	public java.lang.String getGChengwei1() {
		return get("g_chengwei1");
	}

	public void setGChengwei2(java.lang.String gChengwei2) {
		set("g_chengwei2", gChengwei2);
	}

	public java.lang.String getGChengwei2() {
		return get("g_chengwei2");
	}

	public void setGChengwei3(java.lang.String gChengwei3) {
		set("g_chengwei3", gChengwei3);
	}

	public java.lang.String getGChengwei3() {
		return get("g_chengwei3");
	}

	public void setGChengwei4(java.lang.String gChengwei4) {
		set("g_chengwei4", gChengwei4);
	}

	public java.lang.String getGChengwei4() {
		return get("g_chengwei4");
	}

	public void setGChengwei5(java.lang.String gChengwei5) {
		set("g_chengwei5", gChengwei5);
	}

	public java.lang.String getGChengwei5() {
		return get("g_chengwei5");
	}

	public void setGChengwei6(java.lang.String gChengwei6) {
		set("g_chengwei6", gChengwei6);
	}

	public java.lang.String getGChengwei6() {
		return get("g_chengwei6");
	}

	public void setGChengwei7(java.lang.String gChengwei7) {
		set("g_chengwei7", gChengwei7);
	}

	public java.lang.String getGChengwei7() {
		return get("g_chengwei7");
	}

	public void setGBirthday1(java.lang.String gBirthday1) {
		set("g_birthday1", gBirthday1);
	}

	public java.lang.String getGBirthday1() {
		return get("g_birthday1");
	}

	public void setGBirthday2(java.lang.String gBirthday2) {
		set("g_birthday2", gBirthday2);
	}

	public java.lang.String getGBirthday2() {
		return get("g_birthday2");
	}

	public void setGBirthday3(java.lang.String gBirthday3) {
		set("g_birthday3", gBirthday3);
	}

	public java.lang.String getGBirthday3() {
		return get("g_birthday3");
	}

	public void setGBirthday4(java.lang.String gBirthday4) {
		set("g_birthday4", gBirthday4);
	}

	public java.lang.String getGBirthday4() {
		return get("g_birthday4");
	}

	public void setGBirthday5(java.lang.String gBirthday5) {
		set("g_birthday5", gBirthday5);
	}

	public java.lang.String getGBirthday5() {
		return get("g_birthday5");
	}

	public void setGBirthday6(java.lang.String gBirthday6) {
		set("g_birthday6", gBirthday6);
	}

	public java.lang.String getGBirthday6() {
		return get("g_birthday6");
	}

	public void setGBirthday7(java.lang.String gBirthday7) {
		set("g_birthday7", gBirthday7);
	}

	public java.lang.String getGBirthday7() {
		return get("g_birthday7");
	}

	public void setGZhengzhi1(java.lang.String gZhengzhi1) {
		set("g_zhengzhi1", gZhengzhi1);
	}

	public java.lang.String getGZhengzhi1() {
		return get("g_zhengzhi1");
	}

	public void setGZhengzhi2(java.lang.String gZhengzhi2) {
		set("g_zhengzhi2", gZhengzhi2);
	}

	public java.lang.String getGZhengzhi2() {
		return get("g_zhengzhi2");
	}

	public void setGZhengzhi3(java.lang.String gZhengzhi3) {
		set("g_zhengzhi3", gZhengzhi3);
	}

	public java.lang.String getGZhengzhi3() {
		return get("g_zhengzhi3");
	}

	public void setGZhengzhi4(java.lang.String gZhengzhi4) {
		set("g_zhengzhi4", gZhengzhi4);
	}

	public java.lang.String getGZhengzhi4() {
		return get("g_zhengzhi4");
	}

	public void setGZhengzhi5(java.lang.String gZhengzhi5) {
		set("g_zhengzhi5", gZhengzhi5);
	}

	public java.lang.String getGZhengzhi5() {
		return get("g_zhengzhi5");
	}

	public void setGZhengzhi6(java.lang.String gZhengzhi6) {
		set("g_zhengzhi6", gZhengzhi6);
	}

	public java.lang.String getGZhengzhi6() {
		return get("g_zhengzhi6");
	}

	public void setGZhengzhi7(java.lang.String gZhengzhi7) {
		set("g_zhengzhi7", gZhengzhi7);
	}

	public java.lang.String getGZhengzhi7() {
		return get("g_zhengzhi7");
	}

	public void setGGongzuodanwei1(java.lang.String gGongzuodanwei1) {
		set("g_gongzuodanwei1", gGongzuodanwei1);
	}

	public java.lang.String getGGongzuodanwei1() {
		return get("g_gongzuodanwei1");
	}

	public void setGGongzuodanwei2(java.lang.String gGongzuodanwei2) {
		set("g_gongzuodanwei2", gGongzuodanwei2);
	}

	public java.lang.String getGGongzuodanwei2() {
		return get("g_gongzuodanwei2");
	}

	public void setGGongzuodanwei3(java.lang.String gGongzuodanwei3) {
		set("g_gongzuodanwei3", gGongzuodanwei3);
	}

	public java.lang.String getGGongzuodanwei3() {
		return get("g_gongzuodanwei3");
	}

	public void setGGongzuodanwei4(java.lang.String gGongzuodanwei4) {
		set("g_gongzuodanwei4", gGongzuodanwei4);
	}

	public java.lang.String getGGongzuodanwei4() {
		return get("g_gongzuodanwei4");
	}

	public void setGGongzuodanwei5(java.lang.String gGongzuodanwei5) {
		set("g_gongzuodanwei5", gGongzuodanwei5);
	}

	public java.lang.String getGGongzuodanwei5() {
		return get("g_gongzuodanwei5");
	}

	public void setGGongzuodanwei6(java.lang.String gGongzuodanwei6) {
		set("g_gongzuodanwei6", gGongzuodanwei6);
	}

	public java.lang.String getGGongzuodanwei6() {
		return get("g_gongzuodanwei6");
	}

	public void setGGongzuodanwei7(java.lang.String gGongzuodanwei7) {
		set("g_gongzuodanwei7", gGongzuodanwei7);
	}

	public java.lang.String getGGongzuodanwei7() {
		return get("g_gongzuodanwei7");
	}

	public void setChengbaodanweiyijian(java.lang.String chengbaodanweiyijian) {
		set("chengbaodanweiyijian", chengbaodanweiyijian);
	}

	public java.lang.String getChengbaodanweiyijian() {
		return get("chengbaodanweiyijian");
	}

	public void setShenpijiguanyijian(java.lang.String shenpijiguanyijian) {
		set("shenpijiguanyijian", shenpijiguanyijian);
	}

	public java.lang.String getShenpijiguanyijian() {
		return get("shenpijiguanyijian");
	}

}
